#!/usr/bin/env php
<?php

require __DIR__.'/find_autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new \PrestaShop\Ptest\Command\Run());
$application->run();